refactor(preact-components): all lang text props now have an enable t…
searchspring/snap-1.0 pull request #13
Opened 2024-10-07 15:33 UTC by chrisFrazier77

…ext prop to match

2024-10-09 17:00 UTC, korgon requested changes
Some of the props appear to not solve the issue at hand - namely that language overlays within Snap Templates will provide `lang` props that would unhide these elements that a theme may want to hide regardless of the language selection.

2024-10-09 19:41 UTC, chrisFrazier77 commented on packages/snap-preact/components/src/components/Organisms/Facet/Facet.tsx
this doesnt hide the entire button, just the text, You still render an icon in the button. So it made sense to me.

2024-10-09 19:42 UTC, korgon commented on packages/snap-preact/components/src/components/Organisms/Facet/Facet.tsx
Yea, makes sense - thanks for clarifying.

2024-10-14 16:32 UTC, korgon approved these changes
Good to go.

2024-10-14 16:32 UTC, merged