Templates e2e testing
searchspring/snap-1.0 pull request #19
Opened 2024-10-23 22:01 UTC by chrisFrazier77

2024-10-30 17:14 UTC, korgon requested changes
Looking good!

2024-11-05 21:22 UTC, chrisFrazier77 commented on packages/snap-preact/components/src/components/Atoms/TemplateSelect/TemplateSelect.tsx
> +
yes

2024-11-05 21:27 UTC, chrisFrazier77 commented on packages/snap-preact-demo/public/templates/index.html
> +				<div id="searchspring-content"></div>
its used for the branchOverrides test. I cant change the id of it unless we want to manually push up an updated branch bundle and change the selector in the target for that build.

2024-11-06 23:50 UTC, korgon reviewed
Looks good - though I think for the search and searchHorizontal tests we will want to find a better way to handle those unique configurations without resorting to using non-Snap Templates configs...

2024-11-06 23:50 UTC, korgon commented on packages/snap-preact-demo/tests/cypress/e2e/templates/searchHorizontal/query.cy.js
This is a bit odd... moving from a template style config to a non-template style config...

2024-11-06 23:50 UTC, korgon commented on packages/snap-preact-demo/tests/cypress/e2e/templates/search/query.cy.js
This is a bit odd... moving from a template style config to a non-template style config...

2024-11-07 17:40 UTC, korgon commented on packages/snap-preact-demo/tests/cypress/e2e/templates/search/query.cy.js
I'm an idiot.

2024-11-07 17:40 UTC, korgon commented on packages/snap-preact-demo/tests/cypress/e2e/templates/searchHorizontal/query.cy.js
I'm an idiot.

2024-11-07 17:40 UTC, korgon approved these changes
I'm an idiot.

2024-11-07 17:40 UTC, merged