Test prefetching
searchspring/snap-1.0 pull request #22
Opened 2024-11-12 16:40 UTC by dkonieczek

2024-11-20 21:39 UTC, dkonieczek commented
Not included in this PR:
- Disable lazy loading for first 4 Result components in Results.tsx
- Prefetching first 4 images:
```
cntrlr.on('afterStore', async ({ controller }: { controller: AbstractController }, next) => {
	// @ts-ignore - store type
	controller.store.results
		.slice(0, 4)
		.map((result: any) => result.mappings.core.imageUrl)
		.forEach((url: any) => {
			console.log('preloading image', url);
			const img = new Image();
			img.src = url;
		});

	await next();
});
```

2024-11-27 22:02 UTC, korgon requested changes
Should we keep all the performance.mark lines in?

2024-11-27 22:02 UTC, korgon commented on packages/snap-preact/src/Snap.tsx
> +	pageType?: 'search' | 'category';
I'm not sure this should be configurable here - the current change is around prefetching, which they could set themselves in the targeter config. I'm thinking we remove this...

In the future for Beacon 2.0 work with search vs. category, I'm thinking we could rely on explicit definition of the page type via context variables OR on the explicit setting of the search controller.

2024-12-03 16:02 UTC, dkonieczek commented
Removed the performance.mark markers since they were from testing. However it could be useful to add in the future throughout the code base.

2024-12-03 18:17 UTC, merged