ss-path attribute
searchspring/snap-1.0 pull request #24
Opened 2024-11-22 17:07 UTC by chrisFrazier77

2024-11-22 19:19 UTC, chrisFrazier77 commented
There is something interesting happening with the treepath prop being spread onto dropdown buttons. you can see this on all of the facet headers. its not the expected 'ss-path' attribute we are creating, but rather the treepath prop being spread on as an attribute. Even though the button component is pulling that prop out before spreading "additionalProps". I believe it has something to do with cloneWithProps, since we are passing the treepath into those props.

2024-11-27 23:32 UTC, korgon requested changes
The `ss-path` should make it easier to identify for CCP usage.

I was unable to test selecting via names due to the bug:
https://github.com/searchspring/snap/issues/1211

2024-11-27 23:32 UTC, korgon commented on packages/snap-preact/components/src/components/Templates/RecommendationBundle/BundleCTA.tsx
Additionally, shouldn't the `ss-path` here include the icon name?
<img width="612" alt="image" src="https://github.com/user-attachments/assets/89683e3a-74e0-4cc7-8126-f571be451a7c">

2024-11-27 23:32 UTC, korgon commented on packages/snap-preact/components/src/components/Templates/RecommendationBundle/BundleCTA.tsx
> +	const modifiedTreePath = treePath?.slice(0, lastPath);
I'm guessing that the `mergeProps()` usage is causing the need for this? Related to a previous comment, what is the purpose of using mergeProps here?

2024-11-27 23:32 UTC, korgon commented on packages/snap-preact/components/src/components/Templates/RecommendationBundle/BundleSelector.tsx
> +			name: 'bundle-selector-icon',
Maybe better named as `bundle-separator` or `bundle-selector-separator` ?

2024-11-27 23:32 UTC, korgon commented on packages/snap-preact/components/src/components/Templates/RecommendationBundle/BundleSelector.tsx
The name is not showing up in the `ss-path` here as expected...
<img width="612" alt="image" src="https://github.com/user-attachments/assets/f172f0f2-4190-440b-8296-6eeb9c904662">

2024-11-27 23:32 UTC, korgon commented on packages/snap-preact/components/src/components/Templates/RecommendationBundle/BundleSelector.tsx
Might be a good idea to give this component a name, as there is a potential to have other checkboxes within the product cart (think custom card) making it hard to target this one specifically...  🤷🏻‍♂️ 
<img width="612" alt="image" src="https://github.com/user-attachments/assets/18500016-daf9-40f5-a4c4-f098a82a4b50">

2024-12-05 00:40 UTC, korgon approved these changes
Working well. I think this is now in a good spot.

2024-12-05 00:44 UTC, merged